// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ20fOjT9i4dhUl30cNa8VfOFBBFyXW-4',
    appId: '1:107339025282:web:16776750dcf7b82748dd9b',
    messagingSenderId: '107339025282',
    projectId: 'fruit-hup-d92db',
    authDomain: 'fruit-hup-d92db.firebaseapp.com',
    storageBucket: 'fruit-hup-d92db.firebasestorage.app',
    measurementId: 'G-YBPYCNKQBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy3ILhvLMfx-z-qYOONf-H81jobHy0cKY',
    appId: '1:107339025282:android:b650abeb19ae210448dd9b',
    messagingSenderId: '107339025282',
    projectId: 'fruit-hup-d92db',
    storageBucket: 'fruit-hup-d92db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlYIDRuv2ZSLkEDhbFN9yqQxt9eXEc9_4',
    appId: '1:107339025282:ios:96cb6a77c563b01148dd9b',
    messagingSenderId: '107339025282',
    projectId: 'fruit-hup-d92db',
    storageBucket: 'fruit-hup-d92db.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlYIDRuv2ZSLkEDhbFN9yqQxt9eXEc9_4',
    appId: '1:107339025282:ios:96cb6a77c563b01148dd9b',
    messagingSenderId: '107339025282',
    projectId: 'fruit-hup-d92db',
    storageBucket: 'fruit-hup-d92db.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ20fOjT9i4dhUl30cNa8VfOFBBFyXW-4',
    appId: '1:107339025282:web:15747d859cbc083948dd9b',
    messagingSenderId: '107339025282',
    projectId: 'fruit-hup-d92db',
    authDomain: 'fruit-hup-d92db.firebaseapp.com',
    storageBucket: 'fruit-hup-d92db.firebasestorage.app',
    measurementId: 'G-VCVR571PQT',
  );
}
